{***************************************************************************}
{                                                                           }
{           LeakCheck for Delphi                                            }
{                                                                           }
{           Copyright (c) 2015 Honza Rames                                  }
{                                                                           }
{           https://bitbucket.org/shadow_cs/delphi-leakcheck                }
{                                                                           }
{***************************************************************************}
{                                                                           }
{  Licensed under the Apache License, Version 2.0 (the "License");          }
{  you may not use this file except in compliance with the License.         }
{  You may obtain a copy of the License at                                  }
{                                                                           }
{      http://www.apache.org/licenses/LICENSE-2.0                           }
{                                                                           }
{  Unless required by applicable law or agreed to in writing, software      }
{  distributed under the License is distributed on an "AS IS" BASIS,        }
{  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. }
{  See the License for the specific language governing permissions and      }
{  limitations under the License.                                           }
{                                                                           }
{***************************************************************************}

  /// <summary>
  ///   Maximum depth of stack traces
  /// </summary>
  MaxStackSize = 64;

  /// <summary>
  ///   Enable sanitation of object pointers in a scanner. The scanner will
  ///   put object through series of tests to determine whether the given
  ///   pointer is valid and some basic class fields are readable.
  ///   (See LeakCheck.GetObjectClass)
  /// </summary>
  ScannerEnableObjectPointerSanitation = True;

